# Generated by Django 5.0 on 2023-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_delete_priority_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', -1), ('Medium', 0), ('High', 1)], default='Low', max_length=10, null=True),
        ),
    ]
