# Generated by Django 5.0 on 2023-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', -1), ('High', 1), ('Medium', 'Medium')], default='Low', max_length=10, null=True),
        ),
    ]
